project:
  type: website
  output-dir: docs
  preview: 
    port: 4005
    browser: true

website:
  title: "Sushobhon Karmakar"
  site-url: "https://sushobhon.github.io/" # makes site links work on your remote site
  # favicon: "resources/img/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: skills.qmd
        text: Skills
      - href: blogs.qmd
        text: Blogs      
      - href: about.qmd
        text: About Me
      - href: resume.qmd
        text: Resume

    right:
      - text: "{{< fa envelope size=large >}}"
        href: mailto:sushobhonkarmakar@gmail.com
      - text: "{{< fa brands linkedin-in size=large >}}"
        href: https://www.linkedin.com/in/sushobhon-karmakar-579403160/
      - text: "{{< fa brands x-twitter size=large >}}"
        href: https://x.com/sushobhon96
      - text: "{{< fa brands github size=large >}}"
        href: https://github.com/sushobhon
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex
    code-block-bg: true
    code-block-border-left: true
    highlight-style: atom-one
    code-line-numbers: true