---
title: "About Me"
subtitle: "Educational, Professional and Personal Background"
from: markdown+emoji
resources:
  - .nojekyll
---

## {{< fa graduation-cap >}} Education
- M. Sc. in Statistics (2020), Indian Institute of Technology (IITK), UP, India.
- B. Sc. in Statistics (2017), Visva-Bharati, WB, India.

## {{< fa user-tie >}} Career History
- Senior Data Scientist at Tiger Analytics (Jan'25 - Present).
- Data Scientist at Tiger Analytics (Jun'23 - Dec'24).
- Senior Analyst at Tiger Analytics (Jun'21 - May'23).
- Analyst at Tiger Analytics (Jan'21 - May'21)

## {{< fa laptop >}} Current Responsibilities
- **Project Management**: Led a cross-functional initiative to enhance business performance visibility. Collaborated closely with stakeholders and ground users, partnering with the Tableau team to develop an intuitive dashboard for actionable segment performance analysis.

- **Supporting:** Provided hands-on guidance to a Data Scientists and a Scenior Analyst in model development and client engagement, consistently driving the timely delivery of high-quality solutions.

- **Mentoring:** Guided a data scientist's development, ensuring a balanced approach to learning and work while cultivating the advanced skills crucial for senior data scientist advancement.

- **Inovation and RnD:** Continuously research and integrate cutting-edge data science advancements to enhance existing models. I develop innovative, data-driven solutions and streamline implementation for the Model Refreshing Team, ensuring clients receive timely, optimized outcomes.

## {{< fa umbrella-beach >}} Things I Love To Do

- Reading and listening to Bengali literatures.
- Exploring new Technologies.
- Cooking Indian Recipies.
- Playing Football and Badminton.